### ISSUE TITLE
Can't get depselect to work

### ISSUE THREAD

**Issue by musahi0128** [shannah/xataface-module-depselect#2]
Hi @shannah ,

Thanks for your work on Xataface, i really appreciate it !!

I have an issue and needed assitance, i can't get depselect to work like i expected.

I have 2 table as depselect source here:
![image](https://user-images.githubusercontent.com/9418340/36983764-cc6caede-20c5-11e8-8ffd-79339c47e9d8.png)
![image](https://user-images.githubusercontent.com/9418340/36983784-d8894858-20c5-11e8-8ee2-372d0a93a51b.png)

i have this on main table's fields.ini:
![image](https://user-images.githubusercontent.com/9418340/36983835-fa58ed3a-20c5-11e8-839a-e0edba8f2933.png)

When i select first option it return as i expected, but it did'nt update the second list of option.
![image](https://user-images.githubusercontent.com/9418340/36984026-77216a2c-20c6-11e8-9d81-4450d3e942ec.png)

is there anything wrong with fields.ini or the table structure?

Thanks for considering helping me (^-^)

**Comment by shannah** [comment]
That setup looks correct.  Check your javascript console for errors.  Also check your php error log to see if anything is reported.  Use the Chrome debugger to check the ajax request that is sent to the server and see what the result it.

**Comment by musahi0128** [comment]
Dear @shannah ,

I finally can make it work, but with different approach.

Is there any way to delete this issue on github because it's irrelevant?

Thanks.

**Comment by shannah** [comment]
What was the workaround?  This still looks like a bug even if you were able to accomplish your goal in a different way.

**Comment by musahi0128** [comment]
Ok then,,

i have this table:
```
CREATE TABLE `tbl_kodepos` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`kelurahan` VARCHAR(100) NOT NULL,
	`kecamatan` VARCHAR(100) NOT NULL,
	`kabupaten` VARCHAR(100) NOT NULL,
	`provinsi` VARCHAR(100) NOT NULL,
	`kodepos` VARCHAR(5) NOT NULL,
	PRIMARY KEY (`id`),
	INDEX `ixkodepos` (`kodepos`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=81249
;
```
It's from here: https://github.com/edwin/database-kodepos-seluruh-indonesia (thanks to @edwin)

I have all of that column on my main table with same column type.

I have to create view for each level of selection (except for kodepos), something like this:
- `select distinct provinsi from tbl_kodepos order by provinsi asc`
- `select distinct provinsi, kabupaten from tbl_kodepos order by kabupaten asc`
- `select distinct kabupaten, kecamatan from tbl_kodepos order by kecamatan asc`
- `select distinct kecamatan, kelurahan from tbl_kodepos order by kelurahan asc`

Then i setup each of that view as table by creating appropriate directory on my table's directory. In the fields.ini of each table i set the _second_ column as key=PRI (except for the first view, as it contain only one column).

Finally on my main table, here is my fields.ini related to this setup:
```
[provinsi]
widget:label = "Provinsi"
widget:type = depselect
widget:table = provinsi
widget:keycol = provinsi
widget:labelcol = provinsi

[kabupaten]
widget:label = "Kabupaten / Kotamadya"
widget:type = depselect
widget:table = kabupaten
widget:keycol = kabupaten
widget:labelcol = kabupaten
widget:filters:provinsi = "$provinsi"

[kecamatan]
widget:label = "Kecamatan"
widget:type = depselect
widget:table = kecamatan
widget:keycol = kecamatan
widget:labelcol = kecamatan
widget:filters:kabupaten = "$kabupaten"

[kelurahan]
widget:label = "Desa / Kelurahan"
widget:type = depselect
widget:table = kelurahan
widget:keycol = kelurahan
widget:labelcol = kelurahan
widget:filters:kecamatan = "$kecamatan"

[kodepos]
widget:label = "Kode Pos"
widget:type = depselect
widget:table = tbl_kodepos
widget:labelcol = kodepos
widget:filters:provinsi = "$provinsi"
widget:filters:kabupaten = "$kabupaten"
widget:filters:kecamatan = "$kecamatan"
widget:filters:kelurahan = "$kelurahan"
```

Now it's working like i expected.

Thanks.
